### ISSUE TITLE
SPARQL_UPDATE=true seems broken

### ISSUE THREAD

**Issue by tkuhn** [tenforce/docker-virtuoso#26]
Setting SPARQL_UPDATE=true via docker-compose file works up to tenforce/virtuoso:1.0.0-virtuoso7.2.4, but it seems broken for more recent versions, including tenforce/virtuoso:latest. I found the workaround to run this on the running container:

    $ docker exec -ti $CONTAINERID bash -c 'echo "GRANT SPARQL_UPDATE to \"SPARQL\";" | isql-v -U dba -P dba'

But I didn't manage to find a workaround to bake this fix into an image.

**Comment by nvdk** [comment]
Hey @tkuhn,

We've looked into this at [redpencil.io](http://redpencil.io/) and can't reproduce the issue. The following command results in a virtuoso setup that allows sparql update queries on the sparql endpoint. 

```docker run -e SPARQL_UPDATE=true -p 8890:8890 tenforce/virtuoso``` 

Note that in docker-compose.yml you will need to specify true as a string. e.g:
```
    environment:
      SPARQL_UPDATE: "true"
```

**Comment by tkuhn** [comment]
You are right, it works with plain docker, but strangely it doesn't via docker-compose. This is the minimal docker-compose.yml file that produces the problem for me:

```
version: '2'
services:
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - 8890:8890
    environment:
      - SPARQL_UPDATE:"true"
```

Any ideas what is going wrong here?

**Comment by tkuhn** [comment]
Wait, it should have been:

```
version: '2'
services:
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - 8890:8890
    environment:
      SPARQL_UPDATE: "true"
```

And now it works! :)
