### ISSUE TITLE
Manifest not found for `tenforce/virtuoso:1.3.2-virtuoso7.2.5`

### ISSUE THREAD

**Issue by aorumbayev** [tenforce/docker-virtuoso#27]
When trying to pull the virtuoso image using docker-compose with the following tag `tenforce/virtuoso:1.3.2-virtuoso7.2.5`. I get the following error :

```
ERROR: manifest for tenforce/virtuoso:1.3.2-virtuoso7.2.5 not found
```

Compose declaration : 

```
database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5
    container_name: my-virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    ports:
      - "8890:8890"
    restart: on-failure
    volumes:
      - ./data/virtuoso:/var/lib/virtuoso/data
```

__OS__ : MacOS 10.14.3
__Docker desktop version__ : 2.0.0.3 (31259)
__Compose version__ : 1.23.2
__Docker engine version__ : 18.09.2
